### ISSUE TITLE
Line 14

### ISSUE THREAD

**Issue by tarcnux** [panique/pdo-debug#1]
original code: 
`$keys[] = '/:'.$key.'/';`
But in my case it worked well without the colon ':'
`$keys[] = '/'.$key.'/';`

**Comment by panique** [comment]
Hmmm... the double colons are the official way PDO works, I have a bad feeling when removing this.

**Comment by panique** [comment]
Let's test this for a long long time! I

**Comment by tarcnux** [comment]
:ok_hand:
