### ISSUE TITLE
converted to string

### ISSUE THREAD

**Issue by rashed86** [panique/pdo-debug#8]
function add_bus_data($value = array())
    {
        $query = $this->db->prepare("INSERT INTO `bus_info` ( `bus_no`, `bus_name`, `source`, `destination`, `arrival_date`, `arrival_time`, `departure_time`,`price`,`status` ,`user_id` ) VALUES (?,?,?,?,?,?,?,?,?,?)");
     /*  */   $query->execute(array($value['bus_no'],$value['bus_name'],$value['source'],$value['destination'],$value['arrival_date'],$value['arrival_time'],$value['departure_time'],$value['price'],'pending', $value['user_id'])) or die(print_r($query->errorInfo(), true));

        echo interpolateQuery($query, $value);

    }

Here,
I am facing problem at this line
 $raw_sql = preg_replace($keys, $values, $raw_sql, 1, $count); 
Where it's says Object of class PDOStatement could not be converted to string. 
How can i solve this

**Comment by panique** [comment]
First please format your code, it's unreadable! You are trying to output something that is probably not a string/integer/etc, maybe do a hard var_dump before
